# Generated by Django 5.1.3 on 2024-12-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_no',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('bill_no', 'id')},
        ),
    ]
